# Generated by Django 4.2.7 on 2023-11-11 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='code',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
