# Generated by Django 4.2.7 on 2023-11-12 13:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_alter_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='replay_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='boards.post'),
        ),
    ]
