# Generated by Django 4.2.7 on 2023-11-12 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0005_reply_replay_time_alter_reply_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
